### ISSUE TITLE
genisoimage not available (MacOS 11.3)

### ISSUE THREAD

**Issue by feedface** [TorgoTorgo/Ghidra-App-Bundle#4]
However, 
replacing with mkisofs seems to work.
You can brew install cdrtools which includes mkisofs

Sorry if this is the wrong way to do this note. I'm a leach, not a contributor!

**Comment by TorgoTorgo** [comment]
I've pushed up a version that uses `hdiutil` to create the dmg. `hdiutil` is bundled with macOS and so you shouldn't need to install anything with `brew`.

Please try this new version.

**Comment by feedface** [comment]
It doesn't seem to catch the exception (not working, still):
[+] Extracted to /var/folders/_2/tjyb3yfs0y51r4b99xdhhkdm0000gq/T/tmp1v5flayo/Ghidra.app/Contents/Resources
[+] Building dmg
/bin/sh: genisoimage: command not found
hdiutil: create: Only one image can be created at a time.
Usage:	hdiutil create <sizespec> [options] <imagepath>
	hdiutil create -help
Traceback (most recent call last):
  File "/Users/robthebrew/Desktop/Ghidra-App-Bundle/./update.py", line 171, in <module>
    subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'genisoimage -V "Ghidra 9.2.2" -D -R -apple -no-pad -o "Ghidra 9.2.2.dmg" "/var/folders/_2/tjyb3yfs0y51r4b99xdhhkdm0000gq/T/tmp1v5flayo"' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robthebrew/Desktop/Ghidra-App-Bundle/./update.py", line 174, in <module>
    subprocess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'hdiutil create -volname "Ghidra 9.2.2" -fs HFS+  -srcfolder "/var/folders/_2/tjyb3yfs0y51r4b99xdhhkdm0000gq/T/tmp1v5flayo" Ghidra 9.2.2.dmg' returned non-zero exit status 1.

**Comment by TorgoTorgo** [comment]
Oh apologies, I see the issue. There's a missing quotation mark.

**Comment by TorgoTorgo** [comment]
I've just pushed a new commit. Please try again, this time it should work.

**Comment by feedface** [comment]
Now it builds the dmg. However, the app bounces once and quits. I have tried code signing with no change. Console is giving me this:
May  5 14:25:48 MacBook-Air com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.gov.nsa.ghidra.13496623.13496627(503)> [19156]
May  5 14:25:48 MacBook-Air com.apple.xpc.launchd[1] (application.gov.nsa.ghidra.13496623.13496627[29810]): Service exited with abnormal code: 127
Note: the build I did using my suggestion in the OP works.
Also possibly related or not:
bash-3.2$ ./update.py --dmg
[!] Neither path nor url were specified!

**Comment by TorgoTorgo** [comment]
Can you please try running the `Ghidra.app/Contents/MacOS/ghidra` script directly from the terminal after building and extracting? The behaviour you described is what happens when the script can't find your JDK. You should at least get some output to help diagnose the issue.

Curious that your build with `mkisofs` works... Can you run the script directly as I described above and compare the output? It might also be worthwhile trying the `--tar` option.

Please note with the codesigning: I have placed the Ghidra install (which contains executables) into `Resources` which is a "non-code place". This will surely lead to an invalid bundle sig if you sign with `--deep`.

**Comment by feedface** [comment]
Sorry, my bad. As I had my successfully built app, I saved the latest as Ghidra 2.app. That screws up the load script as it is hardwired to expect just Ghidra.app. Working successfully once renamed.
However, the ./update.py --dmg does not work without a url (eg as in your second example).
